import Header from '@/components/header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ActiveSectionContextProvider from '@/context/active-section-context'
import ThemeContextProvider from '@/context/theme-context'
import { Toaster } from 'react-hot-toast'
import ThemeSwitch from '@/components/theme-switch'
import { SpeedInsights } from "@vercel/speed-insights/next"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Soulaimane | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=' !scroll-smooth' >
      <body className={`${inter.className}  bg-[#FCF6F5FF] text-gray-950 relative pt-28 sm:pt-36 dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90`}>
   <div
  className="absolute z-[-12] inset-0 h-full w-full bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:33px_33px]"
>
<div className="bg-[#195190FF] absolute top-[-6rem] z-[-10] md:right-[1rem] right-[1rem] h-[66.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem] dark:bg-[#7e393a]"></div>
        
<div className="bg-[#676394] absolute top-[22rem] z-[-11] left-[-35rem] h-[99.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-11rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]"></div>
<div className="bg-[#195190FF] absolute bottom-[-6rem] z-[-10] md:right-[1rem] right-[1rem] h-[50.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem] dark:bg-[#7e393a]"></div>
        
<div className="bg-[#ABD1C9FF] absolute bottom-[22rem] z-[-11] left-[-35rem] h-[44.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-11rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]"></div>
      
</div>
    
        <ThemeContextProvider>
          <ActiveSectionContextProvider>
            
            <Header />
            {children}
         <SpeedInsights/>
            <Toaster position="top-right" />
            <ThemeSwitch />
          </ActiveSectionContextProvider>
        </ThemeContextProvider>


       

     
        </body>
    </html>
  )
}
      